name: Build Flutter APK 

on:
  push:
    branches:
      - production

jobs:
  upload:
    name: Build Flutter APK 
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'  # Use the version of Flutter you want

    - name: Install dependencies
      run: flutter pub get  # Install Flutter dependencies

        #5 Setup Keystore
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=keystore.jks" >> android/key.properties

    - name: Build Apk
      run: flutter build apk

        #9 Upload Artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: |
          build/app/outputs/flutter-apk/app-release.apk